import jsPDF from "jspdf";

interface MissionStats {
  waypoints: number;
  distance: number;
  area: number;
  flightTime: number;
  gsd: number;
  photos: number;
  batteriesNeeded: number;
  batteryPercent: number;
  droneName: string;
}

interface FlightParams {
  altitude: number;
  frontOverlap: number;
  sideOverlap: number;
  heading: number;
  speed: number;
  pattern: "single" | "crosshatch";
  crossHeadingOffset: number;
  droneModelIdx: number;
  terrainFollow: boolean;
}

interface TerrainData {
  elevations: number[];
  minElev: number;
  maxElev: number;
}

interface LaancData {
  authorization: "authorized" | "requires_auth" | "prohibited" | "uncontrolled";
  maxAutoAltFt: number;
  message: string;
  details: string[];
  lat: number;
  lng: number;
  zones: { name: string; classLabel: string }[];
}

interface GenerateMissionPDFOptions {
  stats: MissionStats;
  params: FlightParams;
  waypoints: [number, number][];
  mapScreenshot: string; // base64 data URL
  projectName: string;
  terrainData: TerrainData | null;
  perWpAltitudes?: number[];
  laancData?: LaancData;
}

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = Math.round(seconds % 60);
  return `${m}m ${s}s`;
}

export function generateMissionPDF(options: GenerateMissionPDFOptions): Blob {
  const { stats, params, waypoints, mapScreenshot, projectName, terrainData, perWpAltitudes, laancData } = options;
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = margin;

  const addFooter = () => {
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text(`Generated by Dronie · ${new Date().toLocaleString()}`, margin, pageH - 8);
    doc.text(`Page ${doc.getNumberOfPages()}`, pageW - margin, pageH - 8, { align: "right" });
  };

  // --- HEADER ---
  doc.setFillColor(30, 64, 175); // primary blue
  doc.rect(0, 0, pageW, 28, "F");
  doc.setTextColor(255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Mission Summary Report", margin, 14);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(`${projectName} · ${stats.droneName} · ${new Date().toLocaleDateString()}`, margin, 22);
  y = 36;

  // --- MAP SCREENSHOT ---
  try {
    const imgProps = doc.getImageProperties(mapScreenshot);
    const imgW = contentW;
    const imgH = (imgProps.height / imgProps.width) * imgW;
    const maxImgH = 90;
    const finalH = Math.min(imgH, maxImgH);
    doc.addImage(mapScreenshot, "PNG", margin, y, imgW, finalH);
    y += finalH + 6;
  } catch {
    // If screenshot fails, skip
    y += 4;
  }

  // --- FLIGHT STATISTICS ---
  doc.setTextColor(30, 64, 175);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Flight Statistics", margin, y);
  y += 6;

  const statsRows: [string, string][] = [
    ["Drone Model", stats.droneName],
    ["Altitude", `${params.altitude}m${params.terrainFollow ? " (AGL, terrain-following)" : ""}`],
    ["GSD", `${stats.gsd.toFixed(1)} cm/px`],
    ["Area", stats.area < 10000 ? `${stats.area.toFixed(0)} m²` : `${(stats.area / 10000).toFixed(2)} ha`],
    ["Total Distance", stats.distance < 1000 ? `${stats.distance.toFixed(0)} m` : `${(stats.distance / 1000).toFixed(1)} km`],
    ["Flight Time", formatTime(stats.flightTime)],
    ["Photos / Waypoints", `${stats.photos}`],
    ["Pattern", params.pattern === "crosshatch" ? `Crosshatch (${params.crossHeadingOffset}° offset)` : "Single Grid"],
    ["Heading", `${params.heading}°`],
    ["Speed", `${params.speed} m/s`],
    ["Front Overlap", `${params.frontOverlap}%`],
    ["Side Overlap", `${params.sideOverlap}%`],
    ["Batteries Needed", `${stats.batteriesNeeded}`],
  ];

  if (terrainData) {
    statsRows.push(["Min Elevation", `${terrainData.minElev.toFixed(0)}m`]);
    statsRows.push(["Max Elevation", `${terrainData.maxElev.toFixed(0)}m`]);
    statsRows.push(["Elevation Δ", `${(terrainData.maxElev - terrainData.minElev).toFixed(0)}m`]);
  }

  doc.setFontSize(8);
  const rowH = 6;
  const colW = contentW / 2;

  statsRows.forEach((row, i) => {
    if (y > pageH - 25) {
      addFooter();
      doc.addPage();
      y = margin;
    }
    const bgColor = i % 2 === 0 ? 245 : 255;
    doc.setFillColor(bgColor, bgColor, bgColor);
    doc.rect(margin, y - 3.5, contentW, rowH, "F");

    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(row[0], margin + 2, y);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30);
    doc.text(row[1], margin + colW, y);
    y += rowH;
  });

  y += 8;

  // --- LAANC / AIRSPACE AUTHORIZATION ---
  if (laancData) {
    if (y > pageH - 60) {
      addFooter();
      doc.addPage();
      y = margin;
    }

    const laancColors: Record<string, [number, number, number]> = {
      authorized: [22, 163, 74],     // green
      uncontrolled: [22, 163, 74],
      requires_auth: [217, 119, 6],  // amber
      prohibited: [220, 38, 38],     // red
    };
    const statusLabels: Record<string, string> = {
      authorized: "AUTHORIZED",
      uncontrolled: "NO AUTH NEEDED",
      requires_auth: "AUTH REQUIRED",
      prohibited: "PROHIBITED",
    };
    const lColor = laancColors[laancData.authorization] || [100, 100, 100];

    doc.setTextColor(30, 64, 175);
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Airspace Authorization (LAANC)", margin, y);
    y += 7;

    // Status badge
    doc.setFillColor(lColor[0], lColor[1], lColor[2]);
    doc.roundedRect(margin, y - 3.5, 40, 7, 1.5, 1.5, "F");
    doc.setTextColor(255);
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text(statusLabels[laancData.authorization] || "UNKNOWN", margin + 2, y);
    y += 8;

    // Info rows
    const laancRows: [string, string][] = [
      ["Check Location", `${laancData.lat.toFixed(5)}, ${laancData.lng.toFixed(5)}`],
      ["Max Auto-Approval", laancData.maxAutoAltFt > 0 ? `${laancData.maxAutoAltFt} ft AGL` : "N/A"],
      ["Status", laancData.message],
    ];

    doc.setFontSize(8);
    laancRows.forEach((row, i) => {
      if (y > pageH - 25) { addFooter(); doc.addPage(); y = margin; }
      const bgColor = i % 2 === 0 ? 245 : 255;
      doc.setFillColor(bgColor, bgColor, bgColor);
      doc.rect(margin, y - 3.5, contentW, rowH, "F");
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100);
      doc.text(row[0], margin + 2, y);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30);
      doc.text(row[1], margin + colW, y);
      y += rowH;
    });

    // Details
    y += 2;
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80);
    laancData.details.forEach((d) => {
      if (y > pageH - 18) { addFooter(); doc.addPage(); y = margin; }
      doc.text(`• ${d}`, margin + 2, y);
      y += 4.5;
    });

    // Zones list
    if (laancData.zones.length > 0) {
      y += 3;
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(60);
      doc.text(`Airspace Zones Detected (${laancData.zones.length})`, margin + 2, y);
      y += 5;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      laancData.zones.slice(0, 8).forEach((z) => {
        if (y > pageH - 18) { addFooter(); doc.addPage(); y = margin; }
        doc.setTextColor(50);
        doc.text(`${z.name || "Unnamed"} — ${z.classLabel}`, margin + 4, y);
        y += 4.5;
      });
    }

    // Disclaimer
    y += 3;
    doc.setFontSize(6);
    doc.setTextColor(130);
    doc.setFont("helvetica", "italic");
    const disclaimer = "Advisory only. Always verify via an FAA-approved LAANC app (Aloft, AirMap, DroneUp) before flight. Check TFRs and local regulations.";
    doc.text(disclaimer, margin + 2, y, { maxWidth: contentW - 4 });
    y += 10;
  }

  // --- WAYPOINT TABLE ---
  if (y > pageH - 40) {
    addFooter();
    doc.addPage();
    y = margin;
  }

  doc.setTextColor(30, 64, 175);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Waypoint Table", margin, y);
  y += 6;

  // Header row
  doc.setFillColor(30, 64, 175);
  doc.rect(margin, y - 3.5, contentW, rowH, "F");
  doc.setTextColor(255);
  doc.setFontSize(7);
  doc.setFont("helvetica", "bold");
  const cols = ["WP#", "Latitude", "Longitude", "Alt (m)"];
  const colWidths = [12, contentW * 0.32, contentW * 0.32, contentW * 0.2];
  let cx = margin + 2;
  cols.forEach((col, i) => {
    doc.text(col, cx, y);
    cx += colWidths[i];
  });
  y += rowH;

  // Limit to 100 waypoints max for PDF
  const maxWps = Math.min(waypoints.length, 100);
  doc.setFontSize(6.5);

  for (let i = 0; i < maxWps; i++) {
    if (y > pageH - 18) {
      addFooter();
      doc.addPage();
      y = margin;
      // Re-draw header
      doc.setFillColor(30, 64, 175);
      doc.rect(margin, y - 3.5, contentW, rowH, "F");
      doc.setTextColor(255);
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      let hx = margin + 2;
      cols.forEach((col, ci) => {
        doc.text(col, hx, y);
        hx += colWidths[ci];
      });
      y += rowH;
      doc.setFontSize(6.5);
    }

    const bgColor = i % 2 === 0 ? 248 : 255;
    doc.setFillColor(bgColor, bgColor, bgColor);
    doc.rect(margin, y - 3.5, contentW, rowH, "F");
    doc.setTextColor(50);
    doc.setFont("helvetica", "normal");

    const wp = waypoints[i];
    const alt = perWpAltitudes ? perWpAltitudes[i]?.toFixed(1) : params.altitude.toFixed(1);
    const vals = [`${i + 1}`, wp[0].toFixed(7), wp[1].toFixed(7), alt ?? "-"];
    let vx = margin + 2;
    vals.forEach((v, vi) => {
      doc.text(String(v), vx, y);
      vx += colWidths[vi];
    });
    y += rowH;
  }

  if (waypoints.length > maxWps) {
    y += 2;
    doc.setFontSize(7);
    doc.setTextColor(120);
    doc.text(`… ${waypoints.length - maxWps} additional waypoints not shown`, margin + 2, y);
  }

  addFooter();

  return doc.output("blob");
}
