import GuideLayout from "./GuideLayout";

export default function OrthoDsmDtmGuide() {
  return (
    <GuideLayout
      path="/guides/orthomosaic-dsm-dtm"
      title="Orthomosaic vs DSM vs DTM vs Point Cloud — What to Deliver | Dronie"
      description="Plain-English breakdown of orthomosaics, digital surface models, digital terrain models, and point clouds — how each is derived from drone photogrammetry, and which one to send your client."
      h1="Orthomosaic vs DSM vs DTM vs point cloud"
      kicker="Deliverables · 12 min read"
    >
      <p>
        Every drone mapping job ends with the same question from the client: <em>"so what file do I open?"</em>{" "}
        The answer depends on what they actually need — a backdrop for a site plan, a volume calculation, a
        grading surface, or a 3D model for design. This guide breaks down the four core deliverables, how each
        is produced, and when to use which.
      </p>

      <h2>The dense point cloud — the source of truth</h2>
      <p>
        Everything downstream comes from the <strong>dense point cloud</strong>: tens of millions of XYZ-RGB
        points generated by Structure-from-Motion. You can think of it as a 3D scatter plot of every surface the
        cameras could see. Delivered as <code>.las</code> or compressed <code>.laz</code>, it's what surveyors and
        engineers actually want when they're doing precise work in Civil 3D, Carlson, or TBC.
      </p>
      <p>
        Hand over the point cloud when: the client has a surveyor or engineer on the other end, when they need
        cross-sections or custom surfaces, or when accuracy matters more than picture quality.
      </p>

      <h2>The orthomosaic — the picture everyone understands</h2>
      <p>
        An <strong>orthomosaic</strong> is a single seamless top-down image of the site, where every pixel is{" "}
        <em>orthorectified</em> — re-projected so that you're looking straight down at it regardless of where the
        camera actually was. The lens distortion and perspective are removed, so you can measure distances and
        areas directly on it like a map.
      </p>
      <p>
        It's exported as a georeferenced <code>.tif</code> (GeoTIFF) that drops into QGIS, ArcGIS, Civil 3D, or
        any CAD package as a backdrop. Hand it over when: the client is a contractor, architect, marketing team,
        or insurance adjuster who needs to point at things and measure.
      </p>

      <h2>DSM vs DTM — the elevation pair</h2>
      <p>
        These two get confused constantly. Both are elevation rasters; the difference is what's included.
      </p>
      <ul>
        <li>
          <strong>DSM — Digital Surface Model.</strong> Elevation of <em>everything the camera saw on top</em>:
          trees, buildings, equipment, cars. Use for line-of-sight studies, solar shade analysis, canopy heights,
          and any "what does the site look like as it sits today" analysis.
        </li>
        <li>
          <strong>DTM — Digital Terrain Model.</strong> Elevation of <em>the bare earth only</em>, with vegetation
          and structures filtered out. Use for grading design, earthworks volumes against a proposed surface, and
          hydrology.
        </li>
      </ul>
      <p>
        A DTM is harder to produce — you need a ground-classification step that removes non-ground points from
        the cloud before rasterizing. On sites with dense vegetation, photogrammetric DTMs are approximate; this
        is where LiDAR earns its budget.
      </p>

      <h2>Choosing the right deliverable</h2>
      <table>
        <thead>
          <tr><th>If the client needs…</th><th>Send them…</th></tr>
        </thead>
        <tbody>
          <tr><td>A backdrop for a site plan</td><td>Orthomosaic (GeoTIFF) + PDF</td></tr>
          <tr><td>Stockpile volumes</td><td>DSM or point cloud + a volumes report</td></tr>
          <tr><td>Cut/fill against design</td><td>DTM + point cloud</td></tr>
          <tr><td>Roof inspection / facade</td><td>Oblique mesh or splat + point cloud</td></tr>
          <tr><td>Marketing flyover / web tour</td><td>Gaussian splat or textured mesh</td></tr>
          <tr><td>Solar shading / line of sight</td><td>DSM + 3D mesh</td></tr>
          <tr><td>Engineer's design surface</td><td>Point cloud (LAS/LAZ) + DTM</td></tr>
        </tbody>
      </table>

      <h2>Accuracy expectations</h2>
      <p>
        With well-distributed GCPs and a clean flight at 1 cm/px GSD, expect roughly:
      </p>
      <ul>
        <li>Horizontal RMSE: <strong>1.5–3 cm</strong></li>
        <li>Vertical RMSE on bare earth: <strong>3–6 cm</strong></li>
        <li>Vertical RMSE in DTM under medium vegetation: <strong>10–25 cm</strong> (often worse)</li>
      </ul>
      <p>
        If a client quotes a tighter spec than these on a DTM under canopy, push back or scope LiDAR instead.
      </p>

      <h2>File formats to standardize on</h2>
      <ul>
        <li><strong>Orthomosaic:</strong> GeoTIFF (<code>.tif</code>) with embedded CRS. Tile if &gt; 4 GB.</li>
        <li><strong>DSM / DTM:</strong> GeoTIFF, single-band float32, NoData defined.</li>
        <li><strong>Point cloud:</strong> LAZ 1.4 with classification, RGB, and intensity preserved.</li>
        <li><strong>Mesh:</strong> OBJ or glTF with texture atlas; FBX if a video pipeline is involved.</li>
        <li><strong>Contours:</strong> DXF or SHP at the client's contour interval.</li>
      </ul>

      <p>
        Want the full pipeline that produces these? Read the{" "}
        <a href="/guides/drone-photogrammetry">complete drone photogrammetry guide</a>.
      </p>
    </GuideLayout>
  );
}